# Turn on front hallway light for 5 minutes when someone comes home
- alias: Turn on front hallway light when someone comes home
  initial_state: on
  trigger:
    - platform: state
      entity_id: device_tracker.lachlan_lachlan
      to: 'home'
    - platform: state
      entity_id: device_tracker.ashlee_ashlee
      to: 'home'
  condition:
    condition: state
    entity_id: light.porch
    state: 'on'
  action:
    service: script.turn_on
    entity_id: script.hallway_1_timer

# Porch light automation
# - alias: Turn on porch light based on darkness
#   initial_state: on
#   trigger:
#     platform: state
#     entity_id: sensor.is_it_dark
#     to: 'true'
#   action:
#     service: light.turn_on
#     entity_id: light.porch
- alias: Turn porch light on at sunset
  initial_state: on
  trigger:
    platform: sun
    event: sunset
    offset: "-00:15:00"
  action:
    - service: notify.ios_lachlan_iphone
      data:
        title: 'Sunset in 15 minutes'
        message: 'Porch light turning on now'
    - service: light.turn_on
      entity_id: light.porch
- alias: Turn off porch light at 11:00pm
  initial_state: on
  trigger:
    platform: time
    at: '23:00:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.lachlan_lachlan
        state: 'home'
      - condition: state
        entity_id: device_tracker.ashlee_ashlee
        state: 'home'
  action:
    service: light.turn_off
    entity_id: light.porch

- alias: Turn off all lights when nobody home (except porch)
  initial_state: on
  trigger:
    platform: state
    entity_id: group.all_devices
    to: 'not_home'
  condition:
    condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  action:
    service: light.turn_off
    entity_id: light.bedroom, light.hallway_1, light.hallway_2, light.theatre

# Light off while using TV in bedroom
- alias: Bedroom playing
  initial_state: on
  trigger:
    platform: state
    entity_id: media_player.bedroom
    to: 'playing'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.sexy_time
      state: 'off'
  action:
    service: light.turn_off
    entity_id: light.bedroom

# Reset boolean at midnight (shitty workaround to allow the above automation to work)
- alias: Turn off sexy time boolean
  initial_state: on
  trigger:
    platform: time
    at: '00:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.sexy_time

# Notify when update available
- alias: Update notifications
  initial_state: on
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.ios_lachlan_iphone
    data:
      title: 'Home Assistant update available'
      message: 'Home Assistant  {{ states.updater.updater.state }}  is now available.'

# Brightness slider
- alias: Bedroom brightness
  initial_state: on
  trigger:
    platform: state
    entity_id: input_number.bedroom_brightness
  action:
    service: light.turn_on
    data_template:
      entity_id: light.bedroom
      brightness: '{{ trigger.to_state.state | int }}'

- alias: SSL expiry notification
  initial_state: on
  trigger:
    platform: numeric_state
    entity_id: sensor.ssl_cert_expiry
    below: 21
  action:
    service: notify.ios_lachlan_iphone
    data:
      title: 'Issue with SSL certificate renewal'
      message: 'Warning - SSL certificate expires in 21 days and has not been automatically renewed'

# Welcome home
- alias: Welcome Ashlee home
  initial_state: on
  trigger:
    platform: state
    entity_id: device_tracker.ashlee_ashlee
    to: 'home'
  action:
    service: tts.google_say
    entity_id: media_player.living_room_speaker
    data:
      message: 'Welcome home Ashlee'
- alias: Welcome Lachlan home
  initial_state: on
  trigger:
    platform: state
    entity_id: device_tracker.lachlan_lachlan
    to: 'home'
  action:
    service: tts.google_say
    entity_id: media_player.living_room_speaker
    data:
      message: 'Welcome home Lochlan'

# Change what is displayed when Guest Mode is on
- alias: Remove components for Guest Mode
  initial_state: on
  trigger:
    platform: state
    entity_id: input_boolean.guest_mode
    to: 'on'
  action:
    - service: group.set_visibility
      entity_id: group.scenes
      data:
        visible: false
    - service: group.set_visibility
      entity_id: group.scene_switches
      data:
        visible: false
    - service: group.set_visibility
      entity_id: group.system_tasks
      data:
        visible: false
- alias: Replace components when Guest Mode is switched off
  initial_state: on
  trigger:
    platform: state
    entity_id: input_boolean.guest_mode
    to: 'off'
  action:
    - service: group.set_visibility
      entity_id: group.scenes
      data:
        visible: true
    - service: group.set_visibility
      entity_id: group.scene_switches
      data:
        visible: true
    - service: group.set_visibility
      entity_id: group.system_tasks
      data:
        visible: true

# Only allow either guest mode or holiday mode, not both
- alias: Turn holiday mode off if guest mode is turned on
  initial_state: on
  trigger:
    platform: state
    entity_id: input_boolean.guest_mode
    to: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.holiday_mode
- alias: Turn guest mode off if holiday mode is turned on
  initial_state: on
  trigger:
    platform: state
    entity_id: input_boolean.holiday_mode
    to: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.guest_mode

# Turn everything off when we go to bed
- alias: Lachlan is in bed
  initial_state: on
  trigger:
    platform: state
    entity_id: sensor.lachlans_iphone_battery_state
    from: 'Unplugged'
    to: 'Charging'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.iphone_battery_state
        state: 'Charging'
      - condition: state
        entity_id: device_tracker.lachlan_lachlan
        state: 'home'
      - condition: state
        entity_id: device_tracker.ashlee_ashlee
        state: 'home'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: time
        after: '21:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: group.all_lights
- alias: Ashlee is in bed
  initial_state: on
  trigger:
    platform: state
    entity_id: sensor.iphone_battery_state
    from: 'Unplugged'
    to: 'Charging'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.lachlans_iphone_battery_state
        state: 'Charging'
      - condition: state
        entity_id: device_tracker.lachlan_lachlan
        state: 'home'
      - condition: state
        entity_id: device_tracker.ashlee_ashlee
        state: 'home'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: time
        after: '21:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: group.all_lights

# Notification to test darkness sensor
- alias: Notify when dark
  initial_state: on
  trigger:
    platform: state
    entity_id: sensor.is_it_dark
    to: 'true'
  action:
    service: notify.ios_lachlan_iphone
    data:
      title: 'Is it dark?'
      message: Elevation is {{ states.sun.sun.attributes.elevation }} and cloud cover is {{ states('sensor.dark_sky_cloud_coverage') }}.

# Notify me when the disk is getting too full
- alias: Notify on 80% disk use
  initial_state: on
  trigger:
    platform: numeric_state
    entity_id: sensor.disk_used_
    above: 80
  action:
    service: notify.ios_lachlan_iphone
    data:
      title: 'Excessive disk use'
      message: 'Disk use on / now exceeds 80%'
