- platform: template
  sensors:
    bedtime:
      entity_id:
        - input_boolean.pixel2xl_charging
        - sensor.iphone_battery_state
        - device_tracker.lachlan_lachlan
        - device_tracker.ashlee_ashlee
      value_template: >-
        {{ is_state('input_boolean.pixel2xl_charging', 'on')
           and is_state('sensor.iphone_battery_state', 'Charging')
           and is_state('device_tracker.lachlan_lachlan', 'home')
           and is_state('device_tracker.ashlee_ashlee', 'home') }}
