homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 126.00
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Australia/Melbourne
# Customisation
  customize: !include customize.yaml
# Enables the frontend
frontend:
# Groups
group: !include group.yaml
# Enables iOS app features
ios:
# HTTP component
http:
  api_password: !secret http_password
  server_port: 443
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key
  base_url: !secret base_url
# Checks for available updates
updater:
  include_used_components: true
# Discover some devices automatically
discovery:
# View all events in a logbook
logbook:
recorder:
  purge_interval: 7
  purge_keep_days: 7
  exclude:
    domains:
      - group
      - media_player
      - zone
    entities:
      - input_boolean.sexy_time
      - input_number.bedroom_brightness
      - sensor.dark_sky_current_template
      - sensor.dark_sky_hourly_summary
      - sensor.dark_sky_daily_summary
      - sensor.dark_sky_dew_point
      - sensor.dark_sky_icon
      - sensor.dark_sky_minutely_summary
      - sensor.dark_sky_nearest_storm_distance
      - sensor.dark_sky_ozone
      - sensor.dark_sky_precip
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_pressure
      - sensor.dark_sky_summary
      - sensor.dark_sky_summary_template
      - sensor.dark_sky_visibility
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_wind_speed
      - sensor.iphone_battery_level
      - sensor.lachlans_ipad_battery_level
      - sensor.lachlans_ipad_battery_state
      - sensor.pihole_ads_blocked_today
      - sensor.pihole_ads_percentage_blocked_today
      - sensor.pihole_dns_queries_today
      - sensor.ssl_cert_expiry
      - switch.all_lights
history:
# Track the sun
sun:
# Text to speech
tts:
  platform: google
# Configuration menu in the side panel
config:
# Sensors
sensor: !include sensor.yaml
# Binary sensors
binary_sensor: !include binary_sensor.yaml
# Switches
switch: !include switch.yaml
# Google Assistant
google_assistant:
  project_id: homehass-2cd30
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token
  exposed_domains:
    - light
# Presence detection
device_tracker:
  - platform: owntracks_http
  - platform: nmap_tracker
    hosts:
      - 192.168.0.14
      - 192.168.0.77
  - platform: netgear
    host: 192.168.0.1
    username: !secret netgear_username
    password: !secret netgear_password
# All automation
automation: !include automation.yaml
# Media players
media_player: !include media_player.yaml
# Shell commands
shell_command: !include shell_command.yaml
# Scripts
script: !include script.yaml
# WeMo
wemo:
  static:
    - 192.168.0.90
# Input booleans
input_boolean: !include input_boolean.yaml
# Notify
notify:
  - platform: pushbullet
    name: Pushbullet
    api_key: !secret pushbullet_api_key
  - platform: html5
    name: HTML5
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id
# Input sliders
input_number:
  bedroom_brightness:
    name: Brightness
    initial: 255
    min: 1
    max: 255
    step: 63
# Scenes
# scene: !include scene.yaml
