# Living Room Chromecast
- platform: cast
  host: 192.168.0.2
# Bedroom Chromecast
- platform: cast
  host: 192.168.0.6
# Google Home (living room)
- platform: cast
  host: 192.168.0.7
# Google Home (bedroom)
- platform: cast
  host: 192.168.0.8
